#!/usr/bin/env python

import math
import rospy
from tf.transformations import euler_from_quaternion
from geometry_msgs.msg import PoseStamped
from crazyflie_driver.msg import Position
#class transformation:

count = 0

def publish_cmd():
    # Tell the drone to fly 
    global count
    count = count + 1
    cmd = Position()
    cmd.header.stamp = rospy.Time.now()
    cmd.header.frame_id = "map"
    
    cmd.x = 0
    cmd.y = 0
    cmd.z = 0.4
    
    roll, pitch, yaw = euler_from_quaternion((0,0,0, 1))
    
    cmd.yaw = math.degrees(yaw)
    
    pub_cmd.publish(cmd)
    
    

rospy.init_node("fly")
pub_cmd = rospy.Publisher("/cf1/cmd_position", Position, queue_size = 2)


def main():
    rate = rospy.Rate(10) #Hz
    rospy.sleep(2)
    while not rospy.is_shutdown():
        publish_cmd()
        rate.sleep()

if __name__ == '__main__':
    main()
