#!/usr/bin/env python

import rospy
from geometry_msgs.msg import PoseStamped

def goal_callback(msg):
    rospy.loginfo('New goal received:\n%s', msg)

rospy.init_node('navgoal')
sub_goal = rospy.Subscriber('/move_base_simple/goal', PoseStamped, goal_callback)

if __name__ == '__main__':
    rospy.spin()

